## Welcome to your notebook.

#### Run this cell to connect to your GIS and get started:

In [1]:
# from arcgis.gis import GIS
# import contextlib, io
# with contextlib.redirect_stderr(io.StringIO()):
#     gis = GIS("home")

#### Now you are ready to start!

In [2]:
# =============================================================================
# Title: NWS Active Weather Alerts to ArcGIS Feature Layer (Notebook Version)

# GitHub: https://github.com/yagaC64/Spring2026DAEN

# License: https://github.com/yagaC64/Spring2026DAEN/blob/main/LICENSE

# Description: A script for an ArcGIS Notebook that fetches active NWS weather
#              alerts for Puerto Rico, processes them, and updates a target
#              ArcGIS Feature Layer using a Truncate and Add workflow.
# Version: 2.8
#
# Optional: ArcGIS Online Sync
# If you want to publish updates to ArcGIS Online, set:
#   USE_ARCGIS=1
#   NWS_ALERTS_LAYER_ID (or FEATURE_LAYER_ITEM_ID)
# Then re-run the notebook from Cell 1.
# =============================================================================
# What's new in v2.8 (Definitive Geocoding Fix):
# - Reworked the API fallback logic to prevent coordinate overwriting on
#   exploded DataFrames.
# - The script now caches new coordinates and maps them back in a single,
#   safe operation, ensuring distinct coordinates are preserved.
# =============================================================================

# Cell 1: Install and Import Libraries
# =============================================================================
import sys
import subprocess
import logging
import json
import re
from datetime import datetime, timezone
import os  # Added for file diagnostics
from pathlib import Path

# Set USE_ARCGIS=1 to enable ArcGIS Online sync; otherwise run locally.
USE_ARCGIS = os.environ.get("USE_ARCGIS", "").lower() in ("1", "true", "yes")

# Install required libraries in the notebook environment
print("Installing required libraries...")
base_pkgs = ['pandas', 'openpyxl', 'requests']
if USE_ARCGIS:
    base_pkgs.append('arcgis')
subprocess.check_call([sys.executable, '-m', 'pip', 'install', *base_pkgs])
print("Installation complete.")

import pandas as pd
import requests

if USE_ARCGIS:
    from arcgis.gis import GIS
    from arcgis.features import Feature
    from arcgis.geometry import Point, Polygon

# Import display for rich DataFrame output in notebooks
try:
    from IPython.display import display
except ImportError:
    display = print  # Fallback for non-IPython environments

# Configure logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s", stream=sys.stdout)

print("\nCell 1: Libraries installed and imported.")

Installing required libraries...

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: openpyxl in /opt/anaconda3/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: requests in /opt/anaconda3/lib/python3.13/site-packages (2.32.5)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: et_xmlfile in /opt/anaconda3/lib/python3.13/site-packages (from openpyxl) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.13/site-packages (from requests) (2026.1.4)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

Installation complete.

Cell 1: Libraries installed and imported.

In [3]:
# Cell 2: Configuration
def resolve_file(filename, env_var=None, search_roots=None):
    if env_var:
        env_val = os.environ.get(env_var)
        if env_val:
            return env_val
    roots = search_roots or [Path.cwd(), Path.cwd().parent, Path.home()]
    arcgis_home = Path("/arcgis/home")
    if arcgis_home.exists():
        roots.append(arcgis_home)
    for root in roots:
        if root.exists():
            match = next(root.rglob(filename), None)
            if match:
                return str(match)
    raise FileNotFoundError("Set the required env var or place the file under the repo or /arcgis/home.")

# =============================================================================
# --- USER-DEFINED VARIABLES ---

FEATURE_LAYER_ITEM_ID = os.environ.get("NWS_ALERTS_LAYER_ID") or os.environ.get("FEATURE_LAYER_ITEM_ID")
LAYER_INDEX = 0

if USE_ARCGIS and not FEATURE_LAYER_ITEM_ID:
    raise ValueError("Set NWS_ALERTS_LAYER_ID (or FEATURE_LAYER_ITEM_ID) in the environment.")

# Local file paths (resolved dynamically)
GEOCODER_FILE = resolve_file("puerto_rico_geocoder_reference.xlsx", env_var="PR_GEOCODER_XLSX")

# Local outputs (for non-ArcGIS runs)
OUTPUT_DIR = Path(os.environ.get("OUTPUT_DIR", "outputs"))
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_CSV = OUTPUT_DIR / "nws_alerts.csv"
OUTPUT_GEOJSON = OUTPUT_DIR / "nws_alerts.geojson"

# NWS API Configuration
ALERTS_URL = "https://api.weather.gov/alerts/active"
HEADERS = {
    "User-Agent": os.environ.get("NWS_USER_AGENT", "DAEN-NWS-Notebook/1.0 (contact)"),
    "Accept": "application/geo+json"
}

print("Cell 2: Configuration variables set.")

Cell 2: Configuration variables set.

In [4]:
# Cell 3: Connect to ArcGIS Organization (optional)
# =============================================================================
if USE_ARCGIS:
    try:
        logging.info("Connecting to ArcGIS environment...")
        gis = GIS("home")
        logging.info("Successfully connected to %s.", gis.properties.portalHostname)
    except Exception as e:
        logging.error(f"FATAL: Failed to connect to ArcGIS. Error: {e}")
        sys.exit(1)

    print("Cell 3: ArcGIS connection established.")
else:
    gis = None
    logging.info("ArcGIS disabled; running locally only.")

2026-04-11 05:37:43,968 - INFO - ArcGIS disabled; running locally only.

In [5]:
# Cell 4: Fetch NWS Alerts
# =============================================================================
# This cell contains the logic to fetch and process NWS alerts.

# --- 4.1: Build Puerto Rico Zone Map ---
pr_zone_map = {}
logging.info("--- Building Puerto Rico Zone Map ---")
try:
    # This map is crucial for translating zone IDs (e.g., PRZ001) to names ("San Juan and Vicinity")
    zones_url = "https://api.weather.gov/zones?area=PR&type=forecast"
    r = requests.get(zones_url, headers=HEADERS, timeout=30)
    r.raise_for_status()
    pr_zones = r.json().get("features", [])
    for zone in pr_zones:
        zone_id = zone.get("properties", {}).get("id")
        zone_name = zone.get("properties", {}).get("name")
        if zone_id and zone_name:
            pr_zone_map[zone_id] = zone_name
    logging.info(f"Successfully mapped {len(pr_zone_map)} PR forecast zones.")
except Exception as e:
    logging.error(f"Could not build PR zone map, using fallbacks. Reason: {e}")
    if not pr_zone_map:
        for i in range(1, 14): pr_zone_map[f"PRZ{i:03d}"] = f"Puerto Rico Zone {i:03d}"

# --- 4.2: Fetch Data ---
all_features = []
logging.info("\n--- Starting Data Fetch ---")
# Strategy 1: Fetch all active US alerts
logging.info(f"Fetching all active US alerts from → {ALERTS_URL}")
try:
    r = requests.get(ALERTS_URL, headers=HEADERS, timeout=90)
    r.raise_for_status()
    nationwide_features = r.json().get("features", [])
    all_features.extend(nationwide_features)
    logging.info(f"Discovered {len(nationwide_features)} total active alerts nationwide.")
except Exception as e:
    logging.warning(f"Failed to fetch nationwide alerts → {e}")

# Strategy 2: Fetch alerts for specific Puerto Rico zones
logging.info("\nFetching alerts for all known PR zones...")
for zone_id in pr_zone_map.keys():
    zone_url = f"https://api.weather.gov/alerts/active/zone/{zone_id}"
    try:
        r = requests.get(zone_url, headers=HEADERS, timeout=30)
        r.raise_for_status()
        zone_features = r.json().get("features", [])
        if zone_features: all_features.extend(zone_features)
    except Exception:
        pass # Failures are expected for zones with no alerts

logging.info("\n--- Data Fetch Complete ---")

# --- 4.3: Deduplicate and Filter ---
unique_features = {f.get("id"): f for f in all_features if f.get("id")}.values()
logging.info(f"Total unique features scraped → {len(unique_features)}")
pr_alerts = []
if unique_features:
    pr_pattern = re.compile(r"puerto\s+rico|PRZ\d{3}|AMZ\d{3}|\bPR\b", re.I)
    text_search_fields = ["areaDesc", "headline", "description"]

    for feature in unique_features:
        properties = feature.get("properties", {})
        is_sanjuan_sender = properties.get("senderName") == "NWS San Juan PR"
        mentions_pr = any(pr_pattern.search(str(properties.get(key, ""))) for key in text_search_fields)

        if is_sanjuan_sender or mentions_pr:
            pr_alerts.append(feature)

logging.info(f"Found {len(pr_alerts)} alerts related to Puerto Rico after filtering.")

print("\nCell 4: NWS Alert data fetching and processing complete.")

2026-04-11 05:37:43,972 - INFO - --- Building Puerto Rico Zone Map ---

2026-04-11 05:37:44,266 - INFO - Successfully mapped 13 PR forecast zones.

2026-04-11 05:37:44,267 - INFO -
--- Starting Data Fetch ---

2026-04-11 05:37:44,268 - INFO - Fetching all active US alerts from → https://api.weather.gov/alerts/active

2026-04-11 05:37:44,928 - INFO - Discovered 240 total active alerts nationwide.

2026-04-11 05:37:44,929 - INFO -
Fetching alerts for all known PR zones...

2026-04-11 05:38:09,200 - INFO -
--- Data Fetch Complete ---

2026-04-11 05:38:09,202 - INFO - Total unique features scraped → 240

2026-04-11 05:38:09,215 - INFO - Found 3 alerts related to Puerto Rico after filtering.

Cell 4: NWS Alert data fetching and processing complete.

In [6]:
# Cell 5: Build and Geocode DataFrame
# =============================================================================
logging.info("--- Building and Geocoding DataFrame ---")
all_records = []
found_zone_ids = set()

# Process real alerts
if pr_alerts:
    for feature in pr_alerts:
        p = feature.get("properties", {})
        affected_zones = [url.split('/')[-1] for url in p.get("affectedZones", [])]
        if not affected_zones:
            affected_zones = [p.get("areaDesc")]
        
        found_zone_ids.update(affected_zones)
        all_records.append({
            "sent": p.get("sent"), "event": p.get("event"), "headline": p.get("headline"),
            "description": p.get("description"), "instruction": p.get("instruction"),
            "response": p.get("response"), "severity": p.get("severity"),
            "urgency": p.get("urgency"), "certainty": p.get("certainty"),
            "expires": p.get("expires"), "status": p.get("status"), "id": p.get("id"),
            "affected_zones": affected_zones
        })

# Add placeholders for zones with no alerts
time_of_check = datetime.now(timezone.utc)
for zone_id, zone_name in pr_zone_map.items():
    if zone_id not in found_zone_ids:
        all_records.append({
            "sent": time_of_check.isoformat(), "event": "No Active Alerts",
            "headline": f"No Active Alerts for {zone_name}", "description": "N/A",
            "instruction": "N/A", "response": "N/A", "severity": "N/A",
            "urgency": "N/A", "certainty": "N/A",
            "expires": None, "status": "None",
            "id": f"placeholder_{zone_id}_{time_of_check.isoformat()}",
            "affected_zones": [zone_id]
        })

if all_records:
    alerts_df = pd.DataFrame(all_records)
    alerts_df = alerts_df.explode('affected_zones').rename(columns={'affected_zones': 'zone_id'})
    logging.info(f"DataFrame exploded. Total records now: {len(alerts_df)}")

    alerts_df['sent'] = pd.to_datetime(alerts_df['sent'], errors='coerce')
    alerts_df['expires'] = pd.to_datetime(alerts_df['expires'], errors='coerce')
    alerts_df['area_desc'] = alerts_df['zone_id'].map(pr_zone_map).fillna(alerts_df['zone_id'])
else:
    alerts_df = pd.DataFrame()

# --- FINAL GEOCODING SWEEP ---
if not alerts_df.empty:
    logging.info("--- STARTING FINAL GEOCODING SWEEP ---")
    # Diagnostics: Check if file exists
    if os.path.exists(GEOCODER_FILE):
        print("Geocoder file found.")
    else:
        print("Geocoder file not found. Set PR_GEOCODER_XLSX or place the file under the repo or /arcgis/home.")

    try:
        geo_df = pd.read_excel(GEOCODER_FILE)
        # Peek at columns for sanity
        print("Geocoder file columns:", geo_df.columns.tolist())
        # Pull extras if present
        cols_to_merge = ['designated_area', 'latitude', 'longitude', 'state']
        if 'geometry_api' in geo_df.columns:
            cols_to_merge.append('geometry_api')
        geo_merge_df = geo_df[cols_to_merge].copy()
        
        # Merge the dataframes, keeping all alerts
        merged_df = pd.merge(
            alerts_df,
            geo_merge_df,
            left_on='area_desc',
            right_on='designated_area',
            how='left'
        )
        merged_df = merged_df.drop(columns=['designated_area'])
        
        # Identify zones that still need coordinates
        zones_to_fetch = merged_df[merged_df['latitude'].isna()]['zone_id'].unique()
        
        # Create a cache to store new coordinates
        new_coords_cache = {}
        
        if len(zones_to_fetch) > 0:
            logging.info(f"Found {len(zones_to_fetch)} zones missing from local file. Attempting live API lookup...")
            for zone_id in zones_to_fetch:
                try:
                    zone_type = 'forecast'
                    if 'PRC' in zone_id: zone_type = 'county'
                    if 'AMZ' in zone_id: zone_type = 'marine'
                    
                    zone_url = f"https://api.weather.gov/zones/{zone_type}/{zone_id}"
                    z_r = requests.get(zone_url, headers=HEADERS, timeout=20)
                    z_r.raise_for_status()
                    z_data = z_r.json()
                    
                    geom_data = z_data.get("geometry")
                    if geom_data and geom_data.get('coordinates'):
                        first_ring = geom_data['coordinates'][0]
                        if geom_data['type'] == 'MultiPolygon':
                            first_ring = first_ring[0]
                        
                        if first_ring:
                            lon_list = [p[0] for p in first_ring]
                            lat_list = [p[1] for p in first_ring]
                            lon = sum(lon_list) / len(lon_list)
                            lat = sum(lat_list) / len(lat_list)
                            state = z_data.get("properties", {}).get("state", "PR")
                            new_coords_cache[zone_id] = {'latitude': lat, 'longitude': lon, 'state': state}
                            # If we want geometry_api from API (as JSON str), add: 'geometry_api': str(geom_data)
                            logging.info(f"✓ Cached API Fallback for '{zone_id}' -> Lat: {lat:.4f}, Lon: {lon:.4f}")
                except Exception as e:
                    logging.warning(f"API lookup failed for '{zone_id}': {e}")

        # Apply the cached coordinates vectorized (preserves dtypes, faster)
        if new_coords_cache:
            missing_mask = merged_df['latitude'].isna()
            for col, cache_key in zip(['latitude', 'longitude', 'state'], ['latitude', 'longitude', 'state']):
                merged_df.loc[missing_mask, col] = merged_df.loc[missing_mask, 'zone_id'].map(lambda z: new_coords_cache.get(z, {}).get(cache_key))
            # If caching geometry_api: zip(['...','geometry_api'], [...'geometry_api']) etc.

        logging.info("--- GEOCODING SWEEP COMPLETE ---")
        alerts_df = merged_df

    except FileNotFoundError:
        logging.warning(f"Geocoder file not found at {GEOCODER_FILE}. Geocoding skipped – no coords added!")
    except Exception as e:
        logging.error(f"Geocoding sweep bombed: {e}")
        import traceback
        traceback.print_exc()  # Spew the full stack for us to dissect


# Display a preview of the full DataFrame
if not alerts_df.empty:
    alerts_df_sorted = alerts_df.sort_values(by=['event', 'area_desc'], ascending=[False, True])
    logging.info("DataFrame Preview:")
    display(alerts_df_sorted)
else:
    logging.info("No records to process.")

print("\nCell 5: DataFrame built and geocoded.")


if not USE_ARCGIS:
    df_out = alerts_df_sorted if "alerts_df_sorted" in locals() else alerts_df
    if df_out is None or df_out.empty:
        logging.info("No records to write locally.")
    else:
        df_out.to_csv(OUTPUT_CSV, index=False)

        def to_jsonable(val):
            if isinstance(val, pd.Timestamp):
                return val.isoformat()
            try:
                if pd.isna(val):
                    return None
            except Exception:
                pass
            if hasattr(val, "item"):
                try:
                    return val.item()
                except Exception:
                    pass
            return val

        features = []
        if {"longitude", "latitude"}.issubset(df_out.columns):
            for _, row in df_out.iterrows():
                lon = row.get("longitude")
                lat = row.get("latitude")
                if pd.notna(lon) and pd.notna(lat):
                    props = row.drop(labels=["longitude", "latitude"]).to_dict()
                    props = {k: to_jsonable(v) for k, v in props.items()}
                    features.append({
                        "type": "Feature",
                        "geometry": {"type": "Point", "coordinates": [float(lon), float(lat)]},
                        "properties": props
                    })
        geojson = {"type": "FeatureCollection", "features": features}
        with open(OUTPUT_GEOJSON, "w", encoding="utf-8") as f:
            json.dump(geojson, f, ensure_ascii=False, indent=2)
        logging.info("Local outputs written: %s and %s", OUTPUT_CSV, OUTPUT_GEOJSON)


if USE_ARCGIS:
    # Cell 6: Access and Truncate Target Feature Layer
    # =============================================================================
    try:
        logging.info("Accessing Feature Layer")
        feature_layer_item = gis.content.get(FEATURE_LAYER_ITEM_ID)
        flayer = feature_layer_item.layers[LAYER_INDEX]
        logging.info(f"Target layer: '{flayer.properties.name}'")

        # Truncate the layer
        count = flayer.query(return_count_only=True)
        logging.info(f"Existing feature count: {count}")
        if count > 0:
            flayer.delete_features(where="1=1")
            logging.info("Layer successfully cleared.")
        else:
            logging.info("Layer is already empty.")
    except Exception as e:
        logging.error(f"FATAL: Could not access or truncate the feature layer. Error: {e}")
        sys.exit(1)

    print("\nCell 6: Feature Layer truncate complete.")


    # Cell 7: Prepare and Push Data to ArcGIS
    # =============================================================================
    if not alerts_df.empty:
        try:
            adds = []
            # Use the sorted dataframe for processing
            df_clean = alerts_df_sorted.copy()

            # Convert datetimes to strings for AGOL
            df_clean['sent'] = df_clean['sent'].dt.strftime('%Y-%m-%d %H:%M:%S').fillna('')
            df_clean['expires'] = df_clean['expires'].dt.strftime('%Y-%m-%d %H:%M:%S').fillna('')

            for _, row in df_clean.iterrows():
                attrs = row.to_dict()
            
                # Clean up potential NaN values and internal columns
                internal_cols = ['zone_id']
                clean_attrs = {k: v for k, v in attrs.items() if k not in internal_cols and pd.notna(v)}

                # Explicitly cast numeric types to prevent silent errors
                if 'latitude' in clean_attrs:
                    clean_attrs['latitude'] = float(clean_attrs['latitude'])
                if 'longitude' in clean_attrs:
                    clean_attrs['longitude'] = float(clean_attrs['longitude'])

                # Create geometry from the now-populated coordinate fields
                geom = None
                if pd.notna(row.get('longitude')) and pd.notna(row.get('latitude')):
                    geom = Point({
                        "x": row['longitude'],
                        "y": row['latitude'],
                        "spatialReference": {"wkid": 4326}
                    })

                adds.append(Feature(geometry=geom, attributes=clean_attrs))

            logging.info(f"Prepared {len(adds)} features for upload.")

            # Push edits to the feature layer
            if adds:
                result = flayer.edit_features(adds=adds, rollback_on_failure=True)
            
                # Verify success
                add_results = result.get("addResults", [])
                success_count = sum(1 for r in add_results if r.get("success"))
                if success_count == len(adds):
                    logging.info(f"✔ Successfully added {success_count} features to the layer.")
                else:
                    logging.error("Some features failed to add. See detailed response:")
                    logging.error(result)
            else:
                logging.info("No features to add.")

        except Exception as e:
            logging.error(f"FATAL: An error occurred while preparing or pushing edits: {e}")
            import traceback
            traceback.print_exc()
            sys.exit(1)
    else:
        logging.info("DataFrame is empty, nothing to push to ArcGIS.")

    print("\n--- WORKFLOW COMPLETE ---")

2026-04-11 05:38:09,234 - INFO - --- Building and Geocoding DataFrame ---

2026-04-11 05:38:09,243 - INFO - DataFrame exploded. Total records now: 175

2026-04-11 05:38:09,305 - INFO - --- STARTING FINAL GEOCODING SWEEP ---

Geocoder file found.

Geocoder file columns: ['designated_area', 'municipio', 'latitude', 'longitude', 'state', 'zipcodes']
2026-04-11 05:38:09,715 - INFO - Found 81 zones missing from local file. Attempting live API lookup...

2026-04-11 05:38:09,904 - INFO - ✓ Cached API Fallback for 'PRC001' -> Lat: 18.1830, Lon: -66.7509

2026-04-11 05:38:10,011 - INFO - ✓ Cached API Fallback for 'PRC003' -> Lat: 18.3616, Lon: -67.1969

2026-04-11 05:38:10,141 - INFO - ✓ Cached API Fallback for 'PRC005' -> Lat: 18.4649, Lon: -67.1316

2026-04-11 05:38:10,272 - INFO - ✓ Cached API Fallback for 'PRC007' -> Lat: 18.2494, Lon: -66.1275

2026-04-11 05:38:10,468 - INFO - ✓ Cached API Fallback for 'PRC009' -> Lat: 18.1374, Lon: -66.2575

2026-04-11 05:38:10,583 - INFO - ✓ Cached API Fallback for 'PRC011' -> Lat: 18.2917, Lon: -67.1479

2026-04-11 05:38:10,751 - INFO - ✓ Cached API Fallback for 'PRC013' -> Lat: 18.4854, Lon: -66.5786

2026-04-11 05:38:10,928 - INFO - ✓ Cached API Fallback for 'PRC015' -> Lat: 17.9882, Lon: -66.0576

2026-04-11 05:38:11,051 - INFO - ✓ Cached API Fallback for 'PRC017' -> Lat: 18.4874, Lon: -66.5473

2026-04-11 05:38:11,161 - INFO - ✓ Cached API Fallback for 'PRC019' -> Lat: 18.1966, Lon: -66.3107

2026-04-11 05:38:11,281 - INFO - ✓ Cached API Fallback for 'PRC021' -> Lat: 18.3503, Lon: -66.1659

2026-04-11 05:38:11,497 - INFO - ✓ Cached API Fallback for 'PRC023' -> Lat: 17.9468, Lon: -67.1224

2026-04-11 05:38:11,619 - INFO - ✓ Cached API Fallback for 'PRC025' -> Lat: 18.2149, Lon: -66.0435

2026-04-11 05:38:11,738 - INFO - ✓ Cached API Fallback for 'PRC027' -> Lat: 18.4387, Lon: -66.8530

2026-04-11 05:38:11,850 - INFO - ✓ Cached API Fallback for 'PRC029' -> Lat: 18.3277, Lon: -65.8877

2026-04-11 05:38:12,039 - INFO - ✓ Cached API Fallback for 'PRC031' -> Lat: 18.4481, Lon: -66.0167

2026-04-11 05:38:12,168 - INFO - ✓ Cached API Fallback for 'PRC033' -> Lat: 18.4459, Lon: -66.1399

2026-04-11 05:38:12,309 - INFO - ✓ Cached API Fallback for 'PRC035' -> Lat: 18.1074, Lon: -66.1446

2026-04-11 05:38:12,503 - INFO - ✓ Cached API Fallback for 'PRC037' -> Lat: 18.2103, Lon: -65.6618

2026-04-11 05:38:12,642 - INFO - ✓ Cached API Fallback for 'PRC039' -> Lat: 18.2732, Lon: -66.5241

2026-04-11 05:38:12,760 - INFO - ✓ Cached API Fallback for 'PRC041' -> Lat: 18.1719, Lon: -66.1720

2026-04-11 05:38:12,923 - INFO - ✓ Cached API Fallback for 'PRC043' -> Lat: 18.1022, Lon: -66.3625

2026-04-11 05:38:13,116 - INFO - ✓ Cached API Fallback for 'PRC045' -> Lat: 18.2259, Lon: -66.2214

2026-04-11 05:38:13,250 - INFO - ✓ Cached API Fallback for 'PRC047' -> Lat: 18.3085, Lon: -66.3303

2026-04-11 05:38:13,366 - INFO - ✓ Cached API Fallback for 'PRC049' -> Lat: 18.2974, Lon: -65.2501

2026-04-11 05:38:13,550 - INFO - ✓ Cached API Fallback for 'PRC051' -> Lat: 18.4579, Lon: -66.2627

2026-04-11 05:38:13,684 - INFO - ✓ Cached API Fallback for 'PRC053' -> Lat: 18.3124, Lon: -65.6096

2026-04-11 05:38:13,795 - INFO - ✓ Cached API Fallback for 'PRC054' -> Lat: 18.3742, Lon: -66.5626

2026-04-11 05:38:13,943 - INFO - ✓ Cached API Fallback for 'PRC055' -> Lat: 17.9296, Lon: -66.9725

2026-04-11 05:38:14,126 - INFO - ✓ Cached API Fallback for 'PRC057' -> Lat: 17.9219, Lon: -66.2137

2026-04-11 05:38:14,242 - INFO - ✓ Cached API Fallback for 'PRC059' -> Lat: 18.0058, Lon: -66.7953

2026-04-11 05:38:14,354 - INFO - ✓ Cached API Fallback for 'PRC061' -> Lat: 18.3669, Lon: -66.1143

2026-04-11 05:38:14,492 - INFO - ✓ Cached API Fallback for 'PRC063' -> Lat: 18.2613, Lon: -65.9808

2026-04-11 05:38:14,691 - INFO - ✓ Cached API Fallback for 'PRC065' -> Lat: 18.4489, Lon: -66.8001

2026-04-11 05:38:14,822 - INFO - ✓ Cached API Fallback for 'PRC067' -> Lat: 18.1375, Lon: -67.1164

2026-04-11 05:38:14,964 - INFO - ✓ Cached API Fallback for 'PRC069' -> Lat: 18.1393, Lon: -65.7978

2026-04-11 05:38:15,164 - INFO - ✓ Cached API Fallback for 'PRC071' -> Lat: 18.4714, Lon: -67.0079

2026-04-11 05:38:15,305 - INFO - ✓ Cached API Fallback for 'PRC073' -> Lat: 18.2167, Lon: -66.5897

2026-04-11 05:38:15,419 - INFO - ✓ Cached API Fallback for 'PRC075' -> Lat: 17.9247, Lon: -66.4555

2026-04-11 05:38:15,555 - INFO - ✓ Cached API Fallback for 'PRC077' -> Lat: 18.2186, Lon: -65.9108

2026-04-11 05:38:15,790 - INFO - ✓ Cached API Fallback for 'PRC079' -> Lat: 17.9487, Lon: -66.9825

2026-04-11 05:38:15,907 - INFO - ✓ Cached API Fallback for 'PRC081' -> Lat: 18.2603, Lon: -66.8536

2026-04-11 05:38:16,032 - INFO - ✓ Cached API Fallback for 'PRC083' -> Lat: 18.2467, Lon: -66.9988

2026-04-11 05:38:16,223 - INFO - ✓ Cached API Fallback for 'PRC085' -> Lat: 18.1884, Lon: -65.8693

2026-04-11 05:38:16,334 - INFO - ✓ Cached API Fallback for 'PRC087' -> Lat: 18.4446, Lon: -65.9750

2026-04-11 05:38:16,480 - INFO - ✓ Cached API Fallback for 'PRC089' -> Lat: 18.3497, Lon: -65.7326

2026-04-11 05:38:16,598 - INFO - ✓ Cached API Fallback for 'PRC091' -> Lat: 18.4822, Lon: -66.5204

2026-04-11 05:38:16,814 - INFO - ✓ Cached API Fallback for 'PRC093' -> Lat: 18.1699, Lon: -66.9474

2026-04-11 05:38:16,930 - INFO - ✓ Cached API Fallback for 'PRC095' -> Lat: 18.0178, Lon: -65.9144

2026-04-11 05:38:17,075 - INFO - ✓ Cached API Fallback for 'PRC097' -> Lat: 18.0884, Lon: -67.8906

2026-04-11 05:38:17,288 - INFO - ✓ Cached API Fallback for 'PRC099' -> Lat: 18.3650, Lon: -67.0876

2026-04-11 05:38:17,415 - INFO - ✓ Cached API Fallback for 'PRC101' -> Lat: 18.3215, Lon: -66.4213

2026-04-11 05:38:17,529 - INFO - ✓ Cached API Fallback for 'PRC103' -> Lat: 18.1156, Lon: -65.7709

2026-04-11 05:38:17,642 - INFO - ✓ Cached API Fallback for 'PRC105' -> Lat: 18.2882, Lon: -66.2516

2026-04-11 05:38:17,830 - INFO - ✓ Cached API Fallback for 'PRC107' -> Lat: 18.2061, Lon: -66.4460

2026-04-11 05:38:17,949 - INFO - ✓ Cached API Fallback for 'PRC109' -> Lat: 18.0182, Lon: -66.0018

2026-04-11 05:38:18,061 - INFO - ✓ Cached API Fallback for 'PRC111' -> Lat: 17.9661, Lon: -66.7541

2026-04-11 05:38:18,269 - INFO - ✓ Cached API Fallback for 'PRC113' -> Lat: 17.8824, Lon: -66.5321

2026-04-11 05:38:18,392 - INFO - ✓ Cached API Fallback for 'PRC115' -> Lat: 18.4520, Lon: -66.9380

2026-04-11 05:38:18,532 - INFO - ✓ Cached API Fallback for 'PRC117' -> Lat: 18.3399, Lon: -67.2259

2026-04-11 05:38:18,654 - INFO - ✓ Cached API Fallback for 'PRC119' -> Lat: 18.3806, Lon: -65.7555

2026-04-11 05:38:18,867 - INFO - ✓ Cached API Fallback for 'PRC121' -> Lat: 18.0816, Lon: -66.9364

2026-04-11 05:38:18,989 - INFO - ✓ Cached API Fallback for 'PRC123' -> Lat: 17.9158, Lon: -66.2454

2026-04-11 05:38:19,120 - INFO - ✓ Cached API Fallback for 'PRC125' -> Lat: 18.1075, Lon: -67.0470

2026-04-11 05:38:19,318 - INFO - ✓ Cached API Fallback for 'PRC127' -> Lat: 18.4344, Lon: -66.0632

2026-04-11 05:38:19,450 - INFO - ✓ Cached API Fallback for 'PRC129' -> Lat: 18.1484, Lon: -65.9817

2026-04-11 05:38:19,614 - INFO - ✓ Cached API Fallback for 'PRC131' -> Lat: 18.3242, Lon: -66.9743

2026-04-11 05:38:19,727 - INFO - ✓ Cached API Fallback for 'PRC133' -> Lat: 17.9209, Lon: -66.3859

2026-04-11 05:38:19,919 - INFO - ✓ Cached API Fallback for 'PRC135' -> Lat: 18.3560, Lon: -66.2525

2026-04-11 05:38:20,027 - INFO - ✓ Cached API Fallback for 'PRC137' -> Lat: 18.4664, Lon: -66.2024

2026-04-11 05:38:20,170 - INFO - ✓ Cached API Fallback for 'PRC139' -> Lat: 18.3338, Lon: -65.9926

2026-04-11 05:38:20,367 - INFO - ✓ Cached API Fallback for 'PRC141' -> Lat: 18.2586, Lon: -66.6947

2026-04-11 05:38:20,483 - INFO - ✓ Cached API Fallback for 'PRC143' -> Lat: 18.4311, Lon: -66.3369

2026-04-11 05:38:20,605 - INFO - ✓ Cached API Fallback for 'PRC145' -> Lat: 18.4910, Lon: -66.3784

2026-04-11 05:38:20,723 - INFO - ✓ Cached API Fallback for 'PRC147' -> Lat: 18.0880, Lon: -65.4726

2026-04-11 05:38:20,926 - INFO - ✓ Cached API Fallback for 'PRC149' -> Lat: 18.1260, Lon: -66.4741

2026-04-11 05:38:21,038 - INFO - ✓ Cached API Fallback for 'PRC151' -> Lat: 18.0681, Lon: -65.8925

2026-04-11 05:38:21,145 - INFO - ✓ Cached API Fallback for 'PRC153' -> Lat: 18.0769, Lon: -66.8592

2026-04-11 05:38:21,414 - WARNING - API lookup failed for 'VIC010': 404 Client Error: Not Found for url: https://api.weather.gov/zones/forecast/VIC010

2026-04-11 05:38:21,646 - WARNING - API lookup failed for 'VIC020': 404 Client Error: Not Found for url: https://api.weather.gov/zones/forecast/VIC020

2026-04-11 05:38:22,205 - WARNING - API lookup failed for 'VIC030': 404 Client Error: Not Found for url: https://api.weather.gov/zones/forecast/VIC030

2026-04-11 05:38:22,209 - INFO - --- GEOCODING SWEEP COMPLETE ---

2026-04-11 05:38:22,213 - INFO - DataFrame Preview:

,sent,event,headline,description,instruction,response,severity,urgency,certainty,expires,status,id,zone_id,area_desc,latitude,longitude,state
5,2026-04-11 03:38:00-04:00,Rip Current Statement,Rip Current Statement issued April 11 at 3:38A...,"* WHAT...High Rip Current Risk, life-threateni...",There is a high risk of rip currents.\n\nRip c...,Avoid,Moderate,Expected,Likely,2026-04-11 11:45:00-04:00,Actual,urn:oid:2.49.0.1.840.0.acf39b1511e1e66c305d63d...,PRZ012,Culebra,18.303052,-65.300099,PR
4,2026-04-11 03:38:00-04:00,Rip Current Statement,Rip Current Statement issued April 11 at 3:38A...,"* WHAT...High Rip Current Risk, life-threateni...",There is a high risk of rip currents.\n\nRip c...,Avoid,Moderate,Expected,Likely,2026-04-11 11:45:00-04:00,Actual,urn:oid:2.49.0.1.840.0.acf39b1511e1e66c305d63d...,PRZ010,Mayaguez and Vicinity,18.199517,-67.202934,PR
2,2026-04-11 03:38:00-04:00,Rip Current Statement,Rip Current Statement issued April 11 at 3:38A...,"* WHAT...High Rip Current Risk, life-threateni...",There is a high risk of rip currents.\n\nRip c...,Avoid,Moderate,Expected,Likely,2026-04-11 11:45:00-04:00,Actual,urn:oid:2.49.0.1.840.0.acf39b1511e1e66c305d63d...,PRZ005,North Central,18.413482,-66.461494,PR
1,2026-04-11 03:38:00-04:00,Rip Current Statement,Rip Current Statement issued April 11 at 3:38A...,"* WHAT...High Rip Current Risk, life-threateni...",There is a high risk of rip currents.\n\nRip c...,Avoid,Moderate,Expected,Likely,2026-04-11 11:45:00-04:00,Actual,urn:oid:2.49.0.1.840.0.acf39b1511e1e66c305d63d...,PRZ002,Northeast,18.376290,-65.904597,PR
3,2026-04-11 03:38:00-04:00,Rip Current Statement,Rip Current Statement issued April 11 at 3:38A...,"* WHAT...High Rip Current Risk, life-threateni...",There is a high risk of rip currents.\n\nRip c...,Avoid,Moderate,Expected,Likely,2026-04-11 11:45:00-04:00,Actual,urn:oid:2.49.0.1.840.0.acf39b1511e1e66c305d63d...,PRZ008,Northwest,18.410383,-66.926935,PR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,2026-04-09 11:19:00-04:00,Hydrologic Outlook,Hydrologic Outlook issued April 9 at 11:19AM A...,ESFSJU\n\nA mid to upper level trough is expec...,None,Monitor,Unknown,Future,Possible,2026-04-11 11:30:00-04:00,Actual,urn:oid:2.49.0.1.840.0.aed0b98c9cfa0f5964798c4...,VIC010,VIC010,NaN,NaN,None
85,2026-04-10 11:19:00-04:00,Hydrologic Outlook,Hydrologic Outlook issued April 10 at 11:19AM ...,ESFSJU\n\nA mid to upper level trough is expec...,None,Monitor,Unknown,Future,Possible,2026-04-11 23:30:00-04:00,Actual,urn:oid:2.49.0.1.840.0.e0f3255c351fcac6c1692cb...,VIC020,VIC020,NaN,NaN,None
166,2026-04-09 11:19:00-04:00,Hydrologic Outlook,Hydrologic Outlook issued April 9 at 11:19AM A...,ESFSJU\n\nA mid to upper level trough is expec...,None,Monitor,Unknown,Future,Possible,2026-04-11 11:30:00-04:00,Actual,urn:oid:2.49.0.1.840.0.aed0b98c9cfa0f5964798c4...,VIC020,VIC020,NaN,NaN,None
86,2026-04-10 11:19:00-04:00,Hydrologic Outlook,Hydrologic Outlook issued April 10 at 11:19AM ...,ESFSJU\n\nA mid to upper level trough is expec...,None,Monitor,Unknown,Future,Possible,2026-04-11 23:30:00-04:00,Actual,urn:oid:2.49.0.1.840.0.e0f3255c351fcac6c1692cb...,VIC030,VIC030,NaN,NaN,None
167,2026-04-09 11:19:00-04:00,Hydrologic Outlook,Hydrologic Outlook issued April 9 at 11:19AM A...,ESFSJU\n\nA mid to upper level trough is expec...,None,Monitor,Unknown,Future,Possible,2026-04-11 11:30:00-04:00,Actual,urn:oid:2.49.0.1.840.0.aed0b98c9cfa0f5964798c4...,VIC030,VIC030,NaN,NaN,None

Cell 5: DataFrame built and geocoded.
2026-04-11 05:38:22,319 - INFO - Local outputs written: outputs/nws_alerts.csv and outputs/nws_alerts.geojson

In [7]:
# pandas full tables
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)
pd.set_option('mode.chained_assignment', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

In [8]:
alerts_df_sorted.info()

<class 'pandas.core.frame.DataFrame'>
Index: 175 entries, 5 to 167
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   sent         168 non-null    datetime64[ns, UTC-04:00]
 1   event        175 non-null    object
 2   headline     175 non-null    object
 3   description  175 non-null    object
 4   instruction  13 non-null     object
 5   response     175 non-null    object
 6   severity     175 non-null    object
 7   urgency      175 non-null    object
 8   certainty    175 non-null    object
 9   expires      168 non-null    datetime64[ns, UTC-04:00]
 10  status       175 non-null    object
 11  id           175 non-null    object
 12  zone_id      175 non-null    object
 13  area_desc    175 non-null    object
 14  latitude     169 non-null    float64
 15  longitude    169 non-null    float64
 16  state        169 non-null    object
dtypes: datetime64[ns, UTC-04:00](2), float64(2), object(13)
memory usage: 24.6+ KB

In [9]:
# display(alerts_df_sorted[["sent","event","headline","description","instruction","response","severity","urgency","certainty","area_desc","expires","status",id	zone_id","latitude","longitude","state","area_desc"]])
display(alerts_df_sorted[["zone_id","event", "latitude","longitude","state","area_desc", "expires"]])
# display(alerts_df_sorted)

,zone_id,event,latitude,longitude,state,area_desc,expires
5,PRZ012,Rip Current Statement,18.303052,-65.300099,PR,Culebra,2026-04-11 11:45:00-04:00
4,PRZ010,Rip Current Statement,18.199517,-67.202934,PR,Mayaguez and Vicinity,2026-04-11 11:45:00-04:00
2,PRZ005,Rip Current Statement,18.413482,-66.461494,PR,North Central,2026-04-11 11:45:00-04:00
1,PRZ002,Rip Current Statement,18.376290,-65.904597,PR,Northeast,2026-04-11 11:45:00-04:00
3,PRZ008,Rip Current Statement,18.410383,-66.926935,PR,Northwest,2026-04-11 11:45:00-04:00
...,...,...,...,...,...,...,...
165,VIC010,Hydrologic Outlook,NaN,NaN,None,VIC010,2026-04-11 11:30:00-04:00
85,VIC020,Hydrologic Outlook,NaN,NaN,None,VIC020,2026-04-11 23:30:00-04:00
166,VIC020,Hydrologic Outlook,NaN,NaN,None,VIC020,2026-04-11 11:30:00-04:00
86,VIC030,Hydrologic Outlook,NaN,NaN,None,VIC030,2026-04-11 23:30:00-04:00
167,VIC030,Hydrologic Outlook,NaN,NaN,None,VIC030,2026-04-11 11:30:00-04:00